version: "3"
services:
  go-server:
    depends_on:
      - postgres
    build: .
    volumes:
      - ../../../:/go/src
    stdin_open: true
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
