version: '3'
services:
  go-server:
    depends_on:
      - sqlite
    build: .
    volumes:
      - ../../../:/go/src
    stdin_open: true
    tty: true

  sqlite:
    image: nouchka/sqlite3:latest
